name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:

env:
  BUILD_TYPE: release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Get CMake and Ninja
      uses: symbitic/install-cmake@master
      with:
        cmake: 3.20.0
        ninja: 1.11.0

    - name: Configure CMake
      run: |
        cmake --version
        ninja --version
        cmake -B ${{github.workspace}}/obj/${{env.BUILD_TYPE}} . -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/sdk/toolchain/toolchain.cmake -DTYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: ninja -C ${{github.workspace}}/obj/${{env.BUILD_TYPE}}

    - name: Set env
      if: ${{ github.event_name == 'release' }}
      run: |
        echo "GITHUB_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo "REPOSITORY_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
        mv .pio/build/release/firmware.bin ${GITHUB_REPOSITORY##*/}-${GITHUB_REF#refs/*/}.bin

    - name: Release
      if: ${{ github.event_name == 'release' }}
      uses: softprops/action-gh-release@v0.1.5
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        files: ${{ env.REPOSITORY_NAME }}-${{ env.GITHUB_TAG }}.bin
      
